Vagrant.configure("2") do |config|
  # Sistema Operacional Base (box)
  config.vm.box = "debian/bookworm64"

  # Nome da VM no VirtualBox
  config.vm.hostname = "debian-lab"

  # Rede privada (apenas a tua máquina acessa)
  config.vm.network "rede_privada", ip: "192.168.56.10"

  # Compartilha uma pasta do teu PC com a VM
  config.vm.synced_folder ".", "/vagrant"

  # Recursos da VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"   # 2GB RAM
    vb.cpus = 2          # 2 CPUs
    vb.name = "debian-lab"
  end

  # Script que roda DENTRO da VM após criar
  config.vm.provision "shell", path: "provision/bootstrap.sh"
end
