# -*- mode: ruby -*-
# vi: set ft=ruby :

# ==========================================
# MÁQUINA VIRTUAL UBUNTU SERVER / ESTUDOS DEVOPS
# ==========================================

Vagrant.configure("2") do |config|
  # Box base: Ubuntu 22.04 LTS (Jammy)
  config.vm.box = "ubuntu/jammy64"

  # Nome da VM
  config.vm.hostname = "ubuntu-lab"

  # Rede Privada (host-only) Apenas o seu PC acessa, ninguém mais!
  config.vm.network "private_network", ip: "192.168.56.13"

  # Pasta compartilhada
  config.vm.synced_folder ".", "/vagrant"

  # Recursos no VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus   = 2
    vb.name   = "estudos-ubuntu-lab"
  end

  # ---------- SSH ----------
  # Garante que o SSH está rodando...
  config.ssh.insert_key = false        # usa a chave padrão do Vagrant (evita recriar toda hora)
  config.ssh.forward_agent = true      # encaminha o agente SSH para dentro da VM (útil pra git/ssh-copy-id)

  # Provisionamento
  config.vm.provision "shell", path: "provision/bootstrap.sh"
end

##########################
# FIM
